# exclude: '\.tsv$|\.csv$|\.maf'
default_language_version:
    python: python3.11
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-yaml
    -   id: check-added-large-files
        args: ['--maxkb=3000']
    -   id: check-merge-conflict
    -   id: no-commit-to-branch
        args:
            [--branch, master]
# -   repo: https://github.com/psf/black
#     rev: 24.3.0
#     hooks:
#     -   id: black
-   repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
    -   id: isort
